version: '3.8'
services:
  trexminer:
    image: trexminer
    build:
      context: .
      dockerfile: Dockerfile3060
    runtime: nvidia
    privileged: true
    restart: always
    command: /opt/t-rex -a ethash --dual-algo-mode a12:r10:lr12 -o stratum+tcp://$POOL1 -u $ETH_WALLET -p x 
 
