version: '3.8'
services:
  ohgodpill:
    image: ohgodpill
    build:
      context: .
      dockerfile: Dockerfile-ohgodpill
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    runtime: nvidia
    depends_on:
      - etherminer
    privileged: true
    restart: always    
    command: /opt/OhGodAnETHlargementPill/OhGodAnETHlargementPill 
