version: '3.8'
services:
  trexminer:
    image: trexminer
    build:
      context: .
      dockerfile: Dockerfile1080
    runtime: nvidia
    privileged: true
    restart: always
    command: /opt/t-rex -a ethash -o stratum+tcp://$POOL1 -u $ETH_WALLET -p x -w $WORKERNAME
 
